<#
.SYNOPSIS
    Creates the upload keystore that signs every public Echo APK.

.DESCRIPTION
    Android identifies an app by its signing key for the life of the install.
    Every build handed to another person must be signed with the SAME key, or
    their phone refuses the update and the only way forward is uninstalling --
    which takes their transcripts with it.

    So this runs once, and the two files it produces must then be backed up
    somewhere that is not this laptop. Both are gitignored on purpose.

        echo-upload.jks        the key itself
        keystore.properties    the passwords, read by app/build.gradle.kts

    Losing them is not recoverable. There is no reset, no support line, and no
    way to re-sign an app someone has already installed.

.PARAMETER Force
    Overwrite an existing keystore. Refuses without this, because overwriting is
    exactly the mistake that orphans every install already in the wild.
#>
[CmdletBinding()]
param(
    [switch]$Force
)

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$storeFile = Join-Path $repoRoot 'echo-upload.jks'
$propsFile = Join-Path $repoRoot 'keystore.properties'
$alias = 'echo-upload'

if ((Test-Path $storeFile) -and -not $Force) {
    Write-Host ''
    Write-Host 'A keystore already exists at:' -ForegroundColor Yellow
    Write-Host "  $storeFile"
    Write-Host ''
    Write-Host 'Refusing to overwrite it. If you replace this key, nobody who has'
    Write-Host 'already installed Echo can ever receive another update -- they would'
    Write-Host 'have to uninstall, losing every transcript on their phone.'
    Write-Host ''
    Write-Host 'Pass -Force only if you are certain no build has been distributed.'
    exit 1
}

# keytool ships with the JDK. Prefer JAVA_HOME so this picks the same JDK 17
# Gradle builds with, rather than whatever happens to be on PATH.
$keytool = if ($env:JAVA_HOME -and (Test-Path (Join-Path $env:JAVA_HOME 'bin\keytool.exe'))) {
    Join-Path $env:JAVA_HOME 'bin\keytool.exe'
} else {
    $found = Get-Command keytool -ErrorAction SilentlyContinue
    if ($null -eq $found) {
        throw 'keytool not found. Set JAVA_HOME to a JDK 17 install, or put keytool on PATH.'
    }
    $found.Source
}

# 24 bytes of CSPRNG, base64'd. Typed by nobody, so length costs nothing.
function New-Password {
    $bytes = New-Object byte[] 24
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    [Convert]::ToBase64String($bytes)
}

# One password, used for both. A PKCS12 keystore cannot hold a key password that
# differs from the store password -- keytool warns and silently ignores the
# -keypass value, after which Gradle fails to open the key with whatever was
# written down here.
$storePassword = New-Password
$keyPassword = $storePassword

Write-Host 'Generating the Echo upload key...' -ForegroundColor Cyan

if (Test-Path $storeFile) { Remove-Item $storeFile -Force }

# 10000 days is the Play minimum for an upload key and is the right order of
# magnitude for a sideloaded one too: an expired key cannot sign an update.
& $keytool -genkeypair `
    -keystore $storeFile `
    -storetype PKCS12 `
    -storepass $storePassword `
    -keypass $keyPassword `
    -alias $alias `
    -keyalg RSA `
    -keysize 4096 `
    -validity 10000 `
    -dname 'CN=Echo, OU=Echo, O=Echo, L=Pune, ST=Maharashtra, C=IN'

if ($LASTEXITCODE -ne 0) { throw "keytool failed with exit code $LASTEXITCODE" }

# Forward slashes: this string is read by Gradle, which treats a backslash as an
# escape even on Windows.
$relativeStore = 'echo-upload.jks'

@"
# Signing material for public Echo builds. GITIGNORED -- never commit this.
#
# Generated by scripts/make-release-key.ps1. Back this file up together with
# echo-upload.jks; without both, no already-installed copy of Echo can ever be
# updated again.
storeFile=$relativeStore
storePassword=$storePassword
keyAlias=$alias
keyPassword=$keyPassword
"@ | Out-File -FilePath $propsFile -Encoding utf8 -NoNewline

Write-Host ''
Write-Host 'Done.' -ForegroundColor Green
Write-Host "  keystore   $storeFile"
Write-Host "  properties $propsFile"
Write-Host ''
Write-Host 'BACK BOTH FILES UP NOW, somewhere that is not this machine.' -ForegroundColor Yellow
Write-Host 'They are gitignored, so a clone of the repo does not contain them, and'
Write-Host 'there is no way to regenerate a key that matches an installed app.'
Write-Host ''
Write-Host 'Then build the public APK with:'
Write-Host '  ./gradlew :app:assembleRelease -PechoDistribution=public -PechoAbi=arm64-v8a'
